### ISSUE TITLE
Automate UI testing

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8589] opened 2015-06-25 20:41 UTC
Would be nice to figure out a way we could automate ui tests (e.g. load the blog page and make sure ckeditor initiates). We're doing much better with backend stuff but as we start more ui dev in 2.x (hopefully?), we'll want a more sustainable way to verify functionality without manual testing of each little refactor/fix/feature.

**Comment by keviocastro** [comment] 2015-06-25 21:45
I like the approach of applying BDD with Behat. I already use my plugins. So I already have the testing and documentation of resources.

**Comment by jdalsem** [comment] 2017-08-07 09:36
Duplicate of #6998

**Closed by jdalsem** 2017-08-07 09:36 UTC
