### ISSUE TITLE
Elgg 2.3.9: profile field access level issue?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12317] opened 2018-12-13 19:31 UTC
Some users seem to have trouble with changing the access level of profile fields. See https://elgg.org/discussion/view/2853957/private-settings-not-saving. Could there be a regression gotten introduced in Elgg 2.3.9?

**Comment by iionly** [comment] 2018-12-19 19:13
@jdalsem the issue was reported for the 2.x branch not 3.x. If it's a regression it might also have been introduced before 2.3.9 as it was later mentioned in the discussion thread.

**Comment by jdalsem** [comment] 2018-12-20 08:34
yeah i saw that... i moved it to the 2.3.x milestone

**Comment by jeabakker** [comment] 2019-04-01 14:08
As far as i can see nothing has changed in Elgg 2.3 ever about how metadata is stored in the database.
Also no changes to the profile/save action.

Closing because not able to reproduce and no clear answer in the discussion about how to reproduce this. Also not clear if maybe some other plugin caused the issue

**Closed by jeabakker** 2019-04-01 14:08 UTC
