### ISSUE TITLE
CKeditor only works on reload

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8456] opened 2015-06-11 10:46 UTC
https://github.com/Elgg/Elgg/issues/8413#issuecomment-111060895 and I swear I've experienced this too, but don't remember which branch. My guess: we're not making the dependencies explicit and so on when resources load immediately from cache, the order of execution is wrong.

**Comment by mrclay** [comment] 2015-06-11 10:50
In general we need to test more thoroughly with Firefox/IE and with simplecache on/off

**Comment by jdalsem** [comment] 2015-07-02 09:15
Still can't reproduce this issue

**Comment by jdalsem** [comment] 2016-04-12 12:28
Closing as there is no way to reproduce the issue... or it resolved itself

**Closed by jdalsem** 2016-04-12 12:28 UTC
Labels: bug, javascript
