### ISSUE TITLE
Invalid use of error_log in _elgg_notify_user()

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8039] opened 2015-03-05 21:13 UTC
https://github.com/Elgg/Elgg/blob/master/engine/lib/notification.php#L358

When should we, if, ever, be using error_log() directly?

**Comment by jdalsem** [comment] 2015-03-05 22:12
dupe of #1494 ?

Only situations could be class destructors or shutdown functions i guess

**Comment by jeabakker** [comment] 2015-04-10 17:33
fixed with #8150

**Closed by jeabakker** 2015-04-10 17:33 UTC
