### ISSUE TITLE
Elgg 3.1 - "action:validate" hook

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12952] opened 2019-12-08 04:29 UTC
I am using spam login filter that uses "action:validate", "register" hook as mentioned below to check for spammer at the time of user registration. 

`elgg_register_plugin_hook_handler("action:validate", "register", __NAMESPACE__ . "\\verify_action_hook");`

If I refer to [learn.elgg.org](http://learn.elgg.org/en/3.1/guides/hooks-list.html#action-hooks) tutorials, its mentioned that I need to return false if I want to terminate the action call. Which I am doing under the "verify_action_hook" function. But it seems like the hook is getting called at the end after user has been created and validation mail has been sent. Ideally the action:validate should be called before the action is called.

Can you please look into this.

**Comment by jeabakker** [comment] 2019-12-09 08:30
The validation hook is triggered in the ActionMiddleware
https://github.com/Elgg/Elgg/blob/2e0a6c15639ad88193d6cf6f4f379826a375f5df/engine/classes/Elgg/Router/Middleware/ActionMiddleware.php#L42-L46

All middleware is executed before the handling of the action/page. So your validation should be before the actual register action. It can be that other validation hooks are triggered before yours.

**Comment by rohit1290** [comment] 2019-12-09 18:35
ok.. i did some testing.. It seems like spam_login_filter is working fine but it is having problem with profile_manager. The hook for profile_manager is called before "action:validate" of spam_login_filter.

Any way I can prioritise the action:validate so that it is called before profile_manager hook?

Note: profile_manger is after spam_login_filter in my plugin list.

**Comment by jeabakker** [comment] 2019-12-10 08:24
As far as i can see Profile Manager is also using a middleware to validate it's input. 
The only way to get before Profile manager would be to add you middleware before profile managers. This can be very tricky.

Why do you need to be before a certain validation? All validation needs to happen at some point

**Comment by rohit1290** [comment] 2019-12-10 09:19
The problem is its creating the user.. then sends the validation mail.. and then it is checking for spammers.. i want to stop the validation mail to be sent..

**Comment by jeabakker** [comment] 2019-12-10 09:36
Maybe the problem is in how Profile manager is handling the register action.

We tried to add some middleware, but maybe we overruled all middleware. This means the ActionMiddleware isn't registered and therefore the 'action:validate', 'register' hook is never called.

**Comment by jdalsem** [comment] 2020-01-08 15:21
Closing this issue as the problem is caused by the Profile Manager plugin

**Closed by jdalsem** 2020-01-08 15:21 UTC
