### ISSUE TITLE
Rearrange private messages into single point, instead of multiple layers

### ISSUE THREAD

**Issue by TNTBOMBOM** [Elgg/Elgg#12322] opened 2018-12-16 13:31 UTC
When someone send me private message , it will open new title in my messages. But when he send another message/text on the same title it will as well show another private message with the same title (where it should be stay on single point/title but multiple texts inside that title).

e.g:

Current:

Sender X

Send Title: Hello (lets say the content "I love you")

Received Title: Hello (I love you 2)

Recipient Y

Received Title: Hello ( I love you)

Send back Title Hello (I love you 2)

Where it Should be:

Sender X

Send Title: Hello (lets say the content "I love you") and on the same place Received Title: Hello (I love you 2)

Recipient Y

Received Title: Hello ( I love you) and Send back Title Hello (I love you 2)

Which mean X and Y will have only one title/subject on there messages but with multiple text inside it. instead of multiple identical titles containing one message each. 

![elgg](https://user-images.githubusercontent.com/11895339/50054119-aafbc800-0136-11e9-8f76-820411f67791.png)

Its better to make it in single place but with flag or sign as new message in the same single place.

**Comment by jdalsem** [comment] 2019-12-12 08:54
Duplicate of https://github.com/Elgg/Elgg/issues/4287

**Closed by jdalsem** 2019-12-12 08:54 UTC
