### ISSUE TITLE
Elgg4: following the link in site notification telling about friend request leads to (profile) page and triggers a fatal error

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#13564] opened 2021-06-14 20:10 UTC
Friendship requests option in Friends plugin settings in enabled.

There's an on-site notification telling me about a pending friend request.

Following the link in this notification leads to a page with the whole body area in blue. Is this intentional? I would doubt it, because I would expect it would cause problems with any site theme used at the latest.

**Comment by daniyaree** [comment] 2021-06-15 05:48
This same blue screen happens in this case also, although here the problem is more: _fatal error_ and _difficulty in posting comments_
https://github.com/Elgg/Elgg/issues/13546

**Comment by jdalsem** [comment] 2021-06-15 07:16
> This same blue screen happens in this case also, although here the problem is more: _fatal error_ and _difficulty in posting comments_
> #13546

i think this is unrelated

**Comment by iionly** [comment] 2021-06-15 17:34
Actually, there IS a fatal error (hadn't scrolled down to see before) and the blue background is probably due to the fatal error (this blue indication an error was new to me).

The fatal error itself is also
```
ELGG.CRITICAL: Exception at time 1623777969:\nPDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'metlb20tconro3a8sgf0s61k74' for key 'PRIMARY'
```
So, maybe different reasons but nevertheless the same error message (I won't post the whole stack trace here).

**Comment by jdalsem** [comment] 2021-06-16 06:31
Solution for the bluescreens (and the related fatal errors) has been found. PR is underway. https://github.com/Elgg/Elgg/pull/13563

**Comment by jdalsem** [comment] 2021-06-16 09:37
Closing this as https://github.com/Elgg/Elgg/pull/13563 is merged and i expected the changes in that PR will fix this issue

**Closed by jdalsem** 2021-06-16 09:37 UTC
