### ISSUE TITLE
Exception when using plugin code_review

### ISSUE THREAD

**Issue by vPriVate** [Elgg/Elgg#9490] opened 2016-03-15 21:59 UTC
After a clean install via composer (starter-project, V2.0.3) I ran into the following exception after activating and using the plugin code review:
```
RecursiveDirectoryIterator::__construct(/path/to/www/elgg/engine/lib/): failed to open dir:
No such file or directory in /path/to/www/elgg/mod/code_review/classes/code_review.php:127
```
It is only possible to see the defined functions, all the other sub-pages of this plugin returning in an error.
Could it be that the wrong folder is addressed (because code_review is in the mod-folder of the root and not within the vendors-folder like elgg core)?

**Comment by juho-jaakkola** [comment] 2016-03-17 06:30
Yes, this is most likely caused by the fact that composer installations have a different directory structure.

**Comment by juho-jaakkola** [comment] 2016-03-17 06:33
I'm closing the issue from here, because the plugin has it's own separate repository:  https://github.com/Srokap/code_review

**Closed by juho-jaakkola** 2016-03-17 06:33 UTC
