### ISSUE TITLE
Sanitize uploaded file names

### ISSUE THREAD

**Issue by michelesbw** [Elgg/Elgg#10608] opened 2016-11-21 15:56 UTC
See discussion here https://github.com/sbwtech/sbw/issues/61
Cheers

**Comment by hypeJunction** [comment] 2016-11-21 16:48
Temporary fix to mitigate download issues: #10608

@mrclay What do you reckon is our strategy with sanitizing file names? Should we go completely nuclear and do it in the filestore class before writing to disk? Should we use a third-party library?

**Comment by feroda** [comment] 2016-11-21 17:00
Thank you a lot @hypeJunction ! 

I think that @da7f17245bcbb426e4 must be applied before uploading any problematic file... am I right? Last night I have tried to do this on an already uploaded file and I got "404 file not found".

What happen to already uploaded files? Is it necessary any script to convert them?

**Comment by hypeJunction** [comment] 2016-11-21 17:26
@feroda We will need to implement some sanitization logic for new files, but we need to make sure that files that have already been uploaded can be downloaded... This is more complicated than it seems.

**Comment by feroda** [comment] 2016-11-22 06:42
@hypeJunction this does not seem to me easy, otherwise I would have proposed a patch / a workaround ;-)

Thanks a lot for your effort in @efc2727 , I am not able to evaluate your code.

**Comment by mrclay** [comment] 2016-11-22 12:25
Isn't the problem just the htmlspecialchars we apply to URL segments? We should start by documenting what's happening at each step.

**Comment by hypeJunction** [comment] 2016-11-22 12:32
The problem is broader. File names can contain `&` or `#` which breaks URL parsing.

**Comment by mrclay** [comment] 2016-11-22 18:59
We should've URL encoded the path in the URL. I thought we were already doing that.

**Comment by hypeJunction** [comment] 2016-11-22 19:04
I tried that but it still fails as a URL segment.

**Comment by mrclay** [comment] 2016-11-22 19:10
Strangely if there's a `%` in the URL at all, Apache won't pass the request to PHP. 😕

**Comment by mrclay** [comment] 2016-11-22 19:31
I think this is an issue with our rewrite strategy. `foo/&bar` in path results in `$_GET['bar']` being set. I'd like to fix that to make it less mysterious.

**Comment by mrclay** [comment] 2016-11-22 20:57
Starting point: #10618

**Comment by feroda** [comment] 2016-11-24 18:11
Sorry @mrclay I am not an Elgg developer, but I don't get the sense to make an effort to use Symfony to solve the problem. Maybe my english is so bad that I have not understood it all.

If I try to restart with the problem that relies in the url encoding as you have said in https://github.com/Elgg/Elgg/issues/10608#issuecomment-262332302 .

@hypeJunction you replied that it fails as an url segment. Is there a way to reproduce this situation? In what it fails as an url segment? can you give me an use case?

Obviously as I have said I am not an Elgg developer and if you think that answering me is just time lost, pls tell me and I will understand ;)

**Comment by feroda** [comment] 2016-11-24 18:45
Are you sure to label it as "easy" ;D.

What the users / elgg social network administrators can do in the meanwhile?

**Comment by hypeJunction** [comment] 2016-12-27 11:25
Fixed by #10673

**Closed by hypeJunction** 2016-12-27 11:25 UTC
Labels: bug, easy
