### ISSUE TITLE
elgg_entity_gatekeeper should return entity on success

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10032] opened 2016-07-27 10:45 UTC
current workflow:
```
elgg_entity_gatekeeper($guid, 'object', 'blog');
$blog = get_entity($guid);
```

could be improved to
```
$blog = elgg_entity_gatekeeper($guid, 'object', 'blog');
```

**Comment by hypeJunction** [comment] 2016-07-27 13:14
I would rather keep elgg_entity_gatekeeper() lightweight.

**Comment by jdalsem** [comment] 2016-07-27 14:30
why? we already load the entity in the function and current return void... what is keeping it lightweight?

**Comment by mrclay** [comment] 2016-07-27 19:36
Duplicate of #8973.

**Closed by mrclay** 2016-07-27 19:36 UTC
