### ISSUE TITLE
title add links causing confusion

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10846] opened 2017-03-22 12:02 UTC
If looking (as admin) to another users blog listing i can 'Add a blog'. That link will make me write a blog (owner admin) in the container of the user. That causes confusion. Do we want to show 'add' links on other user containers? Or only on own...

**Comment by iionly** [comment] 2017-03-22 19:24
The problem is not only with blogs. I've just checked with bookmarks and files. Same problem. Most likely other type of content adding will also have the same problem (at least for core plugins).

I think the Add links should show up on all pages (not only for admins but for all users). Otherwise, it's also confusing (or annoying) if you first have to go to the right page to be able to add content. But of course the container should always match the logged in user (or the group in case of adding content to groups).

**Comment by mrclay** [comment] 2017-03-22 20:26
Duplicate of #6186

**Comment by jdalsem** [comment] 2017-03-23 08:00
Not really duplicate... as #6186 is about the ability to do so, but this ticket is about the fact that it is now easier to be able to do so (probably because of how buttons are added to the title menu)

**Closed** 2017-12-07 11:28 UTC
