### ISSUE TITLE
remove_entity_relationships() does not trigger 'delete' event

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9799] opened 2016-05-06 17:47 UTC
We have a lot of code sniffing relationship state changes. `remove_entity_relationships()` should IMO iterate through all relationships and delete them one by one. Not amazing for performance, but not triggering the event creates a mess.

**Comment by hypeJunction** [comment] 2016-05-06 17:59
See https://github.com/arckinteractive/Roles/pull/20/files

**Comment by mrclay** [comment] 2016-05-06 21:35
Dupe of #5988

**Closed by mrclay** 2016-05-06 21:35 UTC
