### ISSUE TITLE
Likes count

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10928] opened 2017-04-20 10:12 UTC
Currently a 'like' is created with the access_id of the entity being liked. If the access_id of the entity changes the annotation isn't updated.

So different users (logged out, logged in, admin) can have different counters.

Is this intended? And do we want to keep this?

My opinion, likes should be public so everybody sees the same number of likes.

**Comment by mrclay** [comment] 2017-04-20 12:19
Duplicate of #6767, which I think we should revive.

**Closed by mrclay** 2017-04-20 12:19 UTC
Labels: discussion, needs feedback
