### ISSUE TITLE
upgrade redundancy of plugins

### ISSUE THREAD

**Issue by SirbitoX** [Elgg/Elgg#8602] opened 2015-06-27 11:05 UTC
In some plugins like 'groups' and 'thewire' a hook on 'system', 'upgrade' is registered to apply some changes when admin visits http://your-elgg-site.com/upgrade.php (by executing the files in ``` upgrades ``` directory of the plugins). According to UpgradeService scenario it is expected that the upgrade files just run once respect to their version. But in these plugins the upgrade files run every time that admin visits http://your-elgg-site.com/upgrade.php. So I think this way of upgrading is not efficient at all and have a redundant overhead on each hitting the upgrade by admin.
Is it not better to define a upgrade process similar to UpgradeService for the plugins or change UpgradeService somehow it supports upgrading the plugins (i.e. get all upgrade files instead of getting only the files in ``` engine/lib/upgrades/ ``` directory) ??

**Comment by juho-jaakkola** [comment] 2015-06-27 11:56
Duplicate of #5054

**Closed by juho-jaakkola** 2015-06-27 11:56 UTC
