### ISSUE TITLE
[Bug]: Can't Login through "/login"

### ISSUE THREAD

**Issue by kmpope** [Elgg/Elgg#13865] opened 2022-01-08 22:27 UTC
### Elgg version

Elgg 3.3.24 

### Source of your Elgg installation

Other

### Describe the bug

I run my site in walled garden mode. Everytime I click the "view and reply" option from email notifications it tries to open then says "you do not have permission to view the page you are trying to access." When I try to login it won't allow me to. I have to go back to the main login page accessed by "/". Even after removing all modifications I have made it still does the same thing. I cannot login through "/login" only "/".

### Steps to reproduce

1. In walled garden mode using Elgg 3.3.24, click "view and reply" in an email notification.
2. Try to login through "/login".
3. Can only login through "/".
...

### Expected behaviour

Prevents login

### Additional notes

The app was loaded through Insallatron on CPanel.

### PHP version

7.4

**Comment by jeabakker** [comment] 2022-01-10 11:14
could you maybe post an example link from an email here.
Replace your site url with `http://example.com/`, this could help us track the issue

**Comment by kmpope** [comment] 2022-01-11 05:20
Jerome,
Thanks for responding to my issue. Please forgive my ignorance but how do I send you an example without providing the actual URL and login credentials? I can create a test user account for you and then delete it later after the issue is resolved. Would that work? Thanks.
Kyle
***@***.*** 

    On Monday, January 10, 2022, 5:14:27 AM CST, Jerôme Bakker ***@***.***> wrote:  
 
 


could you maybe post an example link from an email here.
Replace your site url with http://example.com/, this could help us track the issue

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jeabakker** [comment] 2022-01-11 07:31
We will try to reproduce the issue on out development environment. All we need the link for is to see if maybe there could be an issue in your configuration.
We don't need access to your website in order to try and find the issue.

**Comment by jeabakker** [comment] 2022-01-11 10:26
@kmpope could you also check for us in the `elgg-config/settings.php` file if the value for `$CONFIG->wwwroot` is set to your website URL including `http` or `https` and a trailing `/`

So if your website url is `https://www.example.com/` it should say that and not something like `http://www.example.com`

**Comment by kmpope** [comment] 2022-01-11 15:01
Jerome,
Ok, thanks.  Here is an example from an email link:

To reply or view the original item, click here:
https://example.com/members-section/comment/view/3447/3351

When I follow the link it won't let me login. If I add in "www" it will let me login. The configuration in the elgg-config/settings.php file is:

$CONFIG->wwwroot = "https://www.example.com/members-section/";




So apparently the issue is the"www." It won't let me login without it and the email link omits it. Is that something I can adjust or is it a core file issue? Thanks.
Sincerely
Kyle Pope
***@***.*** 

    On Tuesday, January 11, 2022, 1:31:29 AM CST, Jerôme Bakker ***@***.***> wrote:  
 
 


We will try to reproduce the issue on out development environment. All we need the link for is to see if maybe there could be an issue in your configuration.
We don't need access to your website in order to try and find the issue.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jeabakker** [comment] 2022-01-11 15:11
Could you maybe check something in the database.
In the `config` table is there an entry for `wwwroot`? If so you can remove that entry, also if it's present it'll probably contain the wrong url (without www).

**Comment by kmpope** [comment] 2022-01-11 18:13
Jerome,
If I am looking in the proper place, in cPanel the site URL is set to https://www.example,com/members-section/ as it should be. In phpMyAdmin I don't find an entry in the database associated with the site entitled wwwroot. In Elgg 2.1.2 there was a setting in the Admin section where I could identify the site url but I don't find it in Elgg 3.2.24. Thanks
Sincerely
Kyle Pope
***@***.*** 

    On Tuesday, January 11, 2022, 9:11:39 AM CST, Jerôme Bakker ***@***.***> wrote:  
 
 


Could you maybe check something in the database.
In the config table is there an entry for wwwroot? If so you can remove that entry, also if it's present it'll probably contain the wrong url (without www).

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kmpope** [comment] 2022-01-12 19:53
Jerome,Any ideas where else I could check to see if the wwwroot setting is incorrect? ***@***.***
-------- Original message --------From: Kyle Pope ***@***.***> Date: 1/11/22  12:13 PM  (GMT-06:00) To: Elgg/Elgg ***@***.***>, Elgg/Elgg ***@***.***> Cc: Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) Jerome,If I am looking in the proper place, in cPanel the site URL is set to https://www.example,com/members-section/ as it should be. In phpMyAdmin I don't find an entry in the database associated with the site entitled wwwroot. In Elgg 2.1.2 there was a setting in the Admin section where I could identify the site url but I don't find it in Elgg 3.2.24. ThanksSincerelyKyle ***@***.***
        
        
        
            
                
                
                    On Tuesday, January 11, 2022, 9:11:39 AM CST, Jerôme Bakker ***@***.***> wrote:
                
                
                
                
Could you maybe check something in the database.
In the config table is there an entry for wwwroot? If so you can remove that entry, also if it's present it'll probably contain the wrong url (without www).

**Comment by kmpope** [comment] 2022-01-13 05:54
Jerome,
I have some new clues. Email notifications from Group Mail and Event Calendar events include "www" in the URL of "view and reply" and allow login. So far, email notifications of wire posts and added files do not and prevent logins. My site automatically adds all users to a group and all posts, files, and events are group posts, files, and events. Thanks.
Sincerely
Kyle Pope
***@***.*** 

    On Wednesday, January 12, 2022, 1:53:40 PM CST, kmpope ***@***.***> wrote:  
 
 Jerome,
Any ideas where else I could check to see if the wwwroot setting is incorrect? Thanks.
Sincerely
***@***.***
-------- Original message --------From: Kyle Pope ***@***.***> Date: 1/11/22 12:13 PM (GMT-06:00) To: Elgg/Elgg ***@***.***>, Elgg/Elgg ***@***.***> Cc: Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) 
Jerome,
If I am looking in the proper place, in cPanel the site URL is set to https://www.example,com/members-section/ as it should be. In phpMyAdmin I don't find an entry in the database associated with the site entitled wwwroot. In Elgg 2.1.2 there was a setting in the Admin section where I could identify the site url but I don't find it in Elgg 3.2.24. Thanks
Sincerely
Kyle Pope
***@***.*** 

    On Tuesday, January 11, 2022, 9:11:39 AM CST, Jerôme Bakker ***@***.***> wrote:  
 
 


Could you maybe check something in the database.
In the config table is there an entry for wwwroot? If so you can remove that entry, also if it's present it'll probably contain the wrong url (without www).

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jeabakker** [comment] 2022-01-13 09:13
If sometimes the notifications are correct and sometimes not than I think the issue is with a plugin which modifies the notifications.
Do you know if you have a plugin installed which modifies the notifications?

Have you tried to disable all 3rd party plugins one by one until this issue disappears?

Which 3rd party plugins do you have active? I think I see at least:
- group_tools
- thewire_tools
- event_manager

**Comment by kmpope** [comment] 2022-01-13 14:17
Jerome,Thanks for your response. I will try that. Here are my current active plugins:Activity PagesBlogFront Page DemoElgg Developer ToolsEmbedGarbage CollectorLikesMessage BoardMessagesPagesSearchSite NotificationsSystem LogThe WireUser Validation by EmailMmenuAdmin ToolsAdvanced CommentsBlog ToolsCSV ExporterCustom cssMenu BuilderPages ToolsTheWire ToolsWidget ManagerWidget PackiZAP Videos - revised edition by iionlyCKEditorCKEditor ExtendedEmbed ExtendedCKEditor AddOnsTidypicsImage EnlargerFavicon OverrideUsers OnlineElgg AlertsFileGDocs File PreviewerHTML Email HandlerFreiChatGroupsGroup ToolsProfileProfile ManagerMembersNotificationsTranslation EditorAutosubscibegroupMessage queueNotifications ToolsEvent CalendarCroncheckCrontriggerThank you.SincerelyKyle ***@***.***
-------- Original message --------From: Jerôme Bakker ***@***.***> Date: 1/13/22  3:13 AM  (GMT-06:00) To: Elgg/Elgg ***@***.***> Cc: kmpope ***@***.***>, Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) 
If sometimes the notifications are correct and sometimes not than I think the issue is with a plugin which modifies the notifications.
Do you know if you have a plugin installed which modifies the notifications?
Have you tried to disable all 3rd party plugins one by one until this issue disappears?
Which 3rd party plugins do you have active? I think I see at least:

group_tools
thewire_tools
event_manager

**Comment by kmpope** [comment] 2022-01-14 05:39
Jerôme,I tried your suggestion and may have found a solution. From the non-bundled plugins, one at a time I turned off any that could affect email notifications. I then sent a test email after I deactivated each one and then turned it back on. When these four were each deactivated the URL under "view and reply" included the "www":Advanced NotificationsAdmin ToolsMenu BuilderGroup ToolsOf these four, Advanced Notifications is the least necessary to the functioning of our site. So, I am going to try it without it for awhile and see if it resolves the problem. I'll report back if the problem shows up again. Thanks for your help! Have a great day.SincerelyKyle ***@***.***
-------- Original message --------From: kmpope ***@***.***> Date: 1/13/22  8:17 AM  (GMT-06:00) To: Elgg/Elgg ***@***.***>, Elgg/Elgg ***@***.***> Cc: Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) Jerome,Thanks for your response. I will try that. Here are my current active plugins:Activity PagesBlogFront Page DemoElgg Developer ToolsEmbedGarbage CollectorLikesMessage BoardMessagesPagesSearchSite NotificationsSystem LogThe WireUser Validation by EmailMmenuAdmin ToolsAdvanced CommentsBlog ToolsCSV ExporterCustom cssMenu BuilderPages ToolsTheWire ToolsWidget ManagerWidget PackiZAP Videos - revised edition by iionlyCKEditorCKEditor ExtendedEmbed ExtendedCKEditor AddOnsTidypicsImage EnlargerFavicon OverrideUsers OnlineElgg AlertsFileGDocs File PreviewerHTML Email HandlerFreiChatGroupsGroup ToolsProfileProfile ManagerMembersNotificationsTranslation EditorAutosubscibegroupMessage queueNotifications ToolsEvent CalendarCroncheckCrontriggerThank you.SincerelyKyle ***@***.*** Original message --------From: Jerôme Bakker ***@***.***> Date: 1/13/22  3:13 AM  (GMT-06:00) To: Elgg/Elgg ***@***.***> Cc: kmpope ***@***.***>, Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) 
If sometimes the notifications are correct and sometimes not than I think the issue is with a plugin which modifies the notifications.
Do you know if you have a plugin installed which modifies the notifications?
Have you tried to disable all 3rd party plugins one by one until this issue disappears?
Which 3rd party plugins do you have active? I think I see at least:

group_tools
thewire_tools
event_manager

**Comment by jdalsem** [comment] 2022-01-14 13:15
As this does not appear to be a Elgg core (or Elgg bundled plugin) issue, but a issue with a third party plugin, i am closing this issue.

**Closed by jdalsem** 2022-01-14 13:15 UTC
Labels: bug

**Comment by kmpope** [comment] 2022-01-14 15:44
Sounds good. Thank you.
-------- Original message --------From: Jeroen Dalsem ***@***.***> Date: 1/14/22  7:15 AM  (GMT-06:00) To: Elgg/Elgg ***@***.***> Cc: kmpope ***@***.***>, Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) 
As this does not appear to be a Elgg core (or Elgg bundled plugin) issue, but a issue with a third party plugin, i am closing this issue.

**Comment by kmpope** [comment] 2022-01-14 23:19
Jerôme,I am confused. As in my previous email I disabled Advanced Notifications, but thus afternoon when a Wire post was made the email notification did not include "www." So, I also disabled Admin Tools, but when an email notification was sent it still did not include "www" in the "view and reply" url. The only difference from last night when disabling either of these allowed emails that included "www" was that last night under Develop > Settings I had blocked outgoing email to normal user (allowing only admins to get emails). I know that this morning Jeroen Dalsem closed the issue since it did not appear to involve core files but I am at a loss to explain why this is happening. Any advice? Thanks.SincerelyKyle ***@***.***
-------- Original message --------From: kmpope ***@***.***> Date: 1/13/22  11:39 PM  (GMT-06:00) To: Elgg/Elgg ***@***.***>, Elgg/Elgg ***@***.***> Cc: Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) Jerôme,I tried your suggestion and may have found a solution. From the non-bundled plugins, one at a time I turned off any that could affect email notifications. I then sent a test email after I deactivated each one and then turned it back on. When these four were each deactivated the URL under "view and reply" included the "www":Advanced NotificationsAdmin ToolsMenu BuilderGroup ToolsOf these four, Advanced Notifications is the least necessary to the functioning of our site. So, I am going to try it without it for awhile and see if it resolves the problem. I'll report back if the problem shows up again. Thanks for your help! Have a great day.SincerelyKyle ***@***.*** Original message --------From: kmpope ***@***.***> Date: 1/13/22  8:17 AM  (GMT-06:00) To: Elgg/Elgg ***@***.***>, Elgg/Elgg ***@***.***> Cc: Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) Jerome,Thanks for your response. I will try that. Here are my current active plugins:Activity PagesBlogFront Page DemoElgg Developer ToolsEmbedGarbage CollectorLikesMessage BoardMessagesPagesSearchSite NotificationsSystem LogThe WireUser Validation by EmailMmenuAdmin ToolsAdvanced CommentsBlog ToolsCSV ExporterCustom cssMenu BuilderPages ToolsTheWire ToolsWidget ManagerWidget PackiZAP Videos - revised edition by iionlyCKEditorCKEditor ExtendedEmbed ExtendedCKEditor AddOnsTidypicsImage EnlargerFavicon OverrideUsers OnlineElgg AlertsFileGDocs File PreviewerHTML Email HandlerFreiChatGroupsGroup ToolsProfileProfile ManagerMembersNotificationsTranslation EditorAutosubscibegroupMessage queueNotifications ToolsEvent CalendarCroncheckCrontriggerThank you.SincerelyKyle ***@***.*** Original message --------From: Jerôme Bakker ***@***.***> Date: 1/13/22  3:13 AM  (GMT-06:00) To: Elgg/Elgg ***@***.***> Cc: kmpope ***@***.***>, Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) 
If sometimes the notifications are correct and sometimes not than I think the issue is with a plugin which modifies the notifications.
Do you know if you have a plugin installed which modifies the notifications?
Have you tried to disable all 3rd party plugins one by one until this issue disappears?
Which 3rd party plugins do you have active? I think I see at least:

group_tools
thewire_tools
event_manager

**Comment by kmpope** [comment] 2022-01-17 02:09
Jerôme,UPDATE: I have continued to investigate this issue and discovered that my cron jobs were setup without the "www." So far, since I have corrected that the emails are including the "www." Hopefully that resolves the problem. Thanks.SincerelyKyle ***@***.***
-------- Original message --------From: kmpope ***@***.***> Date: 1/14/22  5:19 PM  (GMT-06:00) To: Elgg/Elgg ***@***.***>, Elgg/Elgg ***@***.***> Cc: Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) Jerôme,I am confused. As in my previous email I disabled Advanced Notifications, but thus afternoon when a Wire post was made the email notification did not include "www." So, I also disabled Admin Tools, but when an email notification was sent it still did not include "www" in the "view and reply" url. The only difference from last night when disabling either of these allowed emails that included "www" was that last night under Develop > Settings I had blocked outgoing email to normal user (allowing only admins to get emails). I know that this morning Jeroen Dalsem closed the issue since it did not appear to involve core files but I am at a loss to explain why this is happening. Any advice? Thanks.SincerelyKyle ***@***.*** Original message --------From: kmpope ***@***.***> Date: 1/13/22  11:39 PM  (GMT-06:00) To: Elgg/Elgg ***@***.***>, Elgg/Elgg ***@***.***> Cc: Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) Jerôme,I tried your suggestion and may have found a solution. From the non-bundled plugins, one at a time I turned off any that could affect email notifications. I then sent a test email after I deactivated each one and then turned it back on. When these four were each deactivated the URL under "view and reply" included the "www":Advanced NotificationsAdmin ToolsMenu BuilderGroup ToolsOf these four, Advanced Notifications is the least necessary to the functioning of our site. So, I am going to try it without it for awhile and see if it resolves the problem. I'll report back if the problem shows up again. Thanks for your help! Have a great day.SincerelyKyle ***@***.*** Original message --------From: kmpope ***@***.***> Date: 1/13/22  8:17 AM  (GMT-06:00) To: Elgg/Elgg ***@***.***>, Elgg/Elgg ***@***.***> Cc: Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) Jerome,Thanks for your response. I will try that. Here are my current active plugins:Activity PagesBlogFront Page DemoElgg Developer ToolsEmbedGarbage CollectorLikesMessage BoardMessagesPagesSearchSite NotificationsSystem LogThe WireUser Validation by EmailMmenuAdmin ToolsAdvanced CommentsBlog ToolsCSV ExporterCustom cssMenu BuilderPages ToolsTheWire ToolsWidget ManagerWidget PackiZAP Videos - revised edition by iionlyCKEditorCKEditor ExtendedEmbed ExtendedCKEditor AddOnsTidypicsImage EnlargerFavicon OverrideUsers OnlineElgg AlertsFileGDocs File PreviewerHTML Email HandlerFreiChatGroupsGroup ToolsProfileProfile ManagerMembersNotificationsTranslation EditorAutosubscibegroupMessage queueNotifications ToolsEvent CalendarCroncheckCrontriggerThank you.SincerelyKyle ***@***.*** Original message --------From: Jerôme Bakker ***@***.***> Date: 1/13/22  3:13 AM  (GMT-06:00) To: Elgg/Elgg ***@***.***> Cc: kmpope ***@***.***>, Mention ***@***.***> Subject: Re: [Elgg/Elgg] [Bug]: Can't Login through "/login" (Issue #13865) 
If sometimes the notifications are correct and sometimes not than I think the issue is with a plugin which modifies the notifications.
Do you know if you have a plugin installed which modifies the notifications?
Have you tried to disable all 3rd party plugins one by one until this issue disappears?
Which 3rd party plugins do you have active? I think I see at least:

group_tools
thewire_tools
event_manager
