### ISSUE TITLE
Community: Cron fatal errors trying to clean up users

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8738] opened 2015-07-14 20:49 UTC
https://github.com/brettp/Bulk-User-Admin/issues/5

**Comment by juho-jaakkola** [comment] 2015-12-31 13:16
PR: https://github.com/brettp/Bulk-User-Admin/pull/7

I'm closing the issue, because the error is not caused by Elgg core.

**Closed by juho-jaakkola** 2015-12-31 13:16 UTC
