### ISSUE TITLE
RSS views have /serve-file URLs that require cookies

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10950] opened 2017-05-02 23:21 UTC

**Comment by hypeJunction** [comment] 2017-05-03 19:10
I never understood usefulness of RSS in an access controlled system. IMO core shouldn't even be supporting out of the box

**Comment by jdalsem** [comment] 2017-08-08 09:35
This is a similar problem as access bound data so marking it as a duplicate of https://github.com/Elgg/Elgg/issues/3643. Removal of RSS in core can be discussed here https://github.com/Elgg/Elgg/issues/11021

**Closed by jdalsem** 2017-08-08 09:35 UTC
