### ISSUE TITLE
Developer Tools: Add outgoing notifications suppression method

### ISSUE THREAD

**Issue by beck24** [Elgg/Elgg#8044] opened 2015-03-07 06:59 UTC
Admin setting to globally disable all outgoing notifications - emails/sms/etc

Ideally capture outgoing notifications as entities to review as a log in an admin page.

See discussion: https://community.elgg.org/discussion/view/2051678/fyi-are-you-using-elggrlo-as-your-localhost-test-server

**Comment by beck24** [comment] 2015-03-08 02:00
Could be useful with the development mode setting described here: https://github.com/Elgg/Elgg/issues/8016

**Comment by iionly** [comment] 2015-03-09 18:49
To me it would make sense to add it as option in the developer plugin, possibly with the option to provide an email address to send all notifications to (I think Cash's plugin does it this way). I don't think there would be a special developement mode necessary for it.

Maybe there could be three different modes: disabled (all emails are sent normally), enabled with email address provided (all emails get sent to it) and enabled with no email address provided (no emails get send).

**Comment by hypeJunction** [comment] 2015-03-09 19:33
To me this sounds like a job to be done by a plugin. In contrast to what @iionly says, the plugin would check if the development mode is on, and disable notifications (or whatever logic the plugin chooses to expose).

**Comment by jdalsem** [comment] 2015-05-26 11:10
This plugin has a similar feature: https://github.com/ColdTrick/test_panel
It limits outgoing mails to admins and people member of specific groups (it also limits site access to the same set of people)

**Comment by ewinslow** [comment] 2015-05-30 00:29
Sounds really cool but not a blocker for 2.0

**Comment by jdalsem** [comment] 2017-08-07 09:13
Duplicate of #8044

**Comment by jdalsem** [comment] 2017-08-07 09:13
Duplicate of #3846

**Closed by jdalsem** 2017-08-07 09:13 UTC
