### ISSUE TITLE
EntityTable::getEntityTypeSubtypeWhereSql bug

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8851] opened 2015-08-14 08:42 UTC
Looking through the code for type_subtype_pairs logic, I would expect the following:

``` php
$options['type_subtype_pairs'] = array(
  'group' => array(ELGG_ENTITIES_NO_VALUE),
);
```

to return all entities of type `group`. However, due to the following line, we end up with ALL entities.

``` php
if ($paired_subtype_ids_str = implode(',', $paired_subtype_ids)) {
    $wheres[] = "({$table}.type = '$paired_type'"
        . " AND {$table}.subtype IN ($paired_subtype_ids_str))";
}
```

that is because `$paired_subtype_ids = array(0);`, and imploded string is `'0'`. 

We are missing and else statement there:

``` php
if ($paired_subtype_ids_str = implode(',', $paired_subtype_ids)) {
    $wheres[] = "({$table}.type = '$paired_type'"
        . " AND {$table}.subtype IN ($paired_subtype_ids_str))";
} else {
    $wheres[] = "({$table}.type = '$paired_type')";
}
```

**Comment by mrclay** [comment] 2015-08-17 16:06
I think you mean `ELGG_ENTITIES_ANY_VALUE`. I would expect the "no value" constant to exclude groups.

**Comment by hypeJunction** [comment] 2015-08-17 16:09
That's not what the code thinks.

**Comment by mrclay** [comment] 2015-08-24 20:19
I don't think this can be fixed without a BC break. The problem is [this line](https://github.com/Elgg/Elgg/blob/1.12/engine/classes/Elgg/Database/EntityTable.php#L786), which fails to convert to an array anything that's falsy. Unfortunately this includes ELGG_ENTITIES_NO_VALUE and ELGG_ENTITIES_ANY_VALUE. Since the array conversion doesn't happen, the code falls through to [this line](https://github.com/Elgg/Elgg/blob/1.12/engine/classes/Elgg/Database/EntityTable.php#L826), which is fine if you used ELGG_ENTITIES_ANY_VALUE, but not if you used ELGG_ENTITIES_NO_VALUE. If you used ELGG_ENTITIES_NO_VALUE, then the type you gave should be *excluded* instead.

**Comment by mrclay** [comment] 2015-08-24 20:24
A fix would allow the subtype pair `['object' => ELGG_ENTITIES_NO_VALUE]` to exclude objects. The fix in #8852 doesn't address this problem.

**Comment by hypeJunction** [comment] 2015-08-24 20:38
Seems counter intuitive. Currently, this produces the exact results that I want, i.e. returns only groups of any subtype:

`'type_subtype_pairs' => array(
	'group' => ELGG_ENTITIES_NO_VALUE,
)`

**Comment by mrclay** [comment] 2015-08-24 20:39
so you think it's intuitive that ELGG_ENTITIES_NO_VALUE and ELGG_ENTITIES_ANY_VALUE produce the same thing?

**Comment by hypeJunction** [comment] 2015-08-24 20:40
We only 4 types, so if anyone wanted to specifically exclude a type, they could just write type_subtype_pairs to list the other 3.

**Comment by mrclay** [comment] 2015-08-24 20:44
I don't understand why ELGG_ENTITIES_NO_VALUE would be assumed to mean "any value". In any case, ELGG_ENTITIES_ANY_VALUE is definitely less ambiguous. I'd suggest we deprecate the use of ELGG_ENTITIES_NO_VALUE in this case and just take it off the table.

**Comment by hypeJunction** [comment] 2015-08-24 20:46
To me it doesn't make any difference, but perhaps it is less ambiguous. Ideally, I would just use an empty array.

**Comment by mrclay** [comment] 2015-08-24 20:51
I'd read an an empty array to mean "there are no acceptable values."

**Comment by hypeJunction** [comment] 2015-08-24 20:52
As you please.

**Comment by mrclay** [comment] 2015-08-24 20:52
The general problem is we're reaching the limits of how much SQL complexity we can hide. Leaky abstractions.

**Comment by hypeJunction** [comment] 2015-08-24 20:54
Whatever the solution, we should document it. I have wasted almost an hour trying to understand what that spaghetti code does.

**Comment by mrclay** [comment] 2015-08-24 22:07
Surprising: [NO_VALUE really means subtype=0 in the DB](https://elgg.org/discussion/reply/view/2311928/2311874).

**Comment by beck24** [comment] 2015-08-24 22:38
I don't find that surprising, as it's doing what it's labeled - No value to me means it should return those with an 'empty' subtype, which at the db level is 0, or stringified ''

**Closed** 2017-12-15 22:18 UTC
