### ISSUE TITLE
[Bug]: Date picker not working on dynamically loaded contents.

### ISSUE THREAD

**Issue by sarathsince85** [Elgg/Elgg#14335] opened 2023-05-21 05:14 UTC
### Elgg version

4.3.7

### Source of your Elgg installation

Elgg.org website

### Describe the bug

Date picker is not working on dynamically loaded contents

### Steps to reproduce

1.
2.
3.
...

### Expected behaviour

Date picker should work in input fields insider ajax loaded contents

**Comment by RiverVanRain** [comment] 2023-05-22 15:42
I can't reproduce this issue.
All works very well for me.

**Comment by jdalsem** [comment] 2023-05-30 07:18
This could be an issue if your ajax loaded content is not loading via the elgg/Ajax module (as it will take care of additional js that needs to be loaded). elgg/Ajax is automatically used for lightbox content (if initialized via `.elgg-lightbox` class name) and if you use the AMD module `elgg/Ajax` and load content via `ajax.view()`.

Closing this for now as we have no way to reproduce

**Closed by jdalsem** 2023-05-30 07:18 UTC
Labels: bug
