### ISSUE TITLE
Get rid of overflow: hidden

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8743] opened 2015-07-17 10:28 UTC
I keep running into issues with multiple selectors having hidden overflow. I don't see any reason why we enforce this. Given that the UI is getting more complex and there are all kinds of absolutely positioned elements (e.g. menus), having hidden overflow only creates problems. I propose we get rid of it.

**Comment by mrclay** [comment] 2015-07-17 11:34
Dupe of https://github.com/Elgg/Elgg/issues/5197 which I reopened. Please see the discussion there because this method of layout was chosen carefully.

**Closed** 2015-07-17 11:34 UTC
