### ISSUE TITLE
master: Bad UX for user-centered discussions

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8757] opened 2015-07-29 03:15 UTC
The discussion/all page lets users create discussion topics, which end up contained by the user and only browsable via the discussion/all page, which is linked only from a breadcrumb from existing topics. They show up in activity feeds, but the discussion/owner pages 404s for them because they aren't groups.

If we're to keep user-contained discussions, we need to fix the discussion/owner page to accept non-groups, and add a "Discussions" link to user owner blocks/hover menus, or some other UI.

**Comment by mrclay** [comment] 2015-07-29 14:32
PR #8761

**Comment by juho-jaakkola** [comment] 2015-07-29 14:36
This is intended behavior. Or at least we shouldn't be restricting discussions only for groups like the PR is doing. We will want to use e.g. plugin projects as containers for discussions.

**Comment by mrclay** [comment] 2015-07-29 14:48
Right now, the discussions/all page is the only place to see topics made from that page, and likely non-admins can't reply to them. This is crazy confusing UX.

**Comment by mrclay** [comment] 2015-07-29 15:00
If this is intended, then we need to fix the discussion/owner page to accept non-groups, and add a "Discussions" link to user owner blocks/hover menus, or some other UI.

**Comment by mrclay** [comment] 2015-07-29 15:30
I updated the issue title/description.

**Comment by mrclay** [comment] 2015-07-29 15:33
Users already have pages, blogs, and wire posts to host discussions, so allowing discussions under users seems superfluous.

**Comment by mrclay** [comment] 2015-07-29 17:44
@juho-jaakkola Please take another look at #8761. This leaves groups as the only enabled context, but uses the likes approach to make it easy to add discussions to other type/subtypes and fixes a bunch of other problems with using a wider variety of containers.

I think it's too late to add the necessary UI to make user-context discussions really work out of the box in 2.0.

**Comment by mrclay** [comment] 2015-07-31 16:42
#8761 was reverted.

**Comment by juho-jaakkola** [comment] 2015-08-06 12:17
I'd be fine with leaving out the UI for user-centered discussions. If we did that, would there still be something else that needs fixing?

Is there a problem only when the container is a user? Is it possible to use ElggObject as a container?

(I haven't looked into the discussions in a while, so I'm a bit confused what exactly is happening.)

**Comment by mrclay** [comment] 2015-08-06 12:44
We need a mechanism for deciding on the discussions/all page and the add form pages whether or not we can display the tittle (add topic) button. That could be just a custom function, but we'd much prefer to use canWriteToContainer() which leads us to the problem of #4231.

The simplest alternative would be to remove the title button from discussions/all and simply 404 the add form if the container isn't a group. That still allows devs to override both (we'll have to on elgg.org), but it would allow us to put off solving #4231 until 3.0

I'm ok doing that.

**Comment by juho-jaakkola** [comment] 2015-08-07 13:59
Did I understand correctly that once #8778 gets merged, we can safely do this:
```php
$object->canWriteToContainer($user, 'object, 'discussion');
```
To determine whether ```$user``` is allowed to create discussions inside ```$object``` regardless of its subtype?

**Comment by mrclay** [comment] 2015-08-09 21:36
Yes. I'd remove the first commit from #8776.

**Comment by juho-jaakkola** [comment] 2015-08-10 05:51
Why do we need a new hook (```'discussions:allow_context', '<type>:<subtype>'```) instead of using ```canWriteToContainer()```?

**Comment by mrclay** [comment] 2015-08-10 11:30
It's not strictly necessary, it just makes registering types a very readable 1-line process: https://github.com/Elgg/Elgg/pull/8776/files#diff-20b56f78ca68ff21f308104b59cd0155R5

Otherwise adding a container type would require full understanding of the container_permissions_check hook.

**Comment by mrclay** [comment] 2015-08-10 11:37
Likes does this to reduce a ton of boilerplate in each plugin; we don't necessarily have to do the same here.

**Comment by juho-jaakkola** [comment] 2015-08-10 12:33
I'm not sure if I want to add yet another hook. I've always liked the fact that Elgg has so generic hooks. I suggest we do not add ```'discussions:allow_context'``` in 2.0 but revise it later.

**Comment by mrclay** [comment] 2015-08-10 19:18
OK

**Comment by mrclay** [comment] 2015-08-15 05:59
The problem with removing the hook is the discussion/owner page, where we need to decide whether to show the page or not, but we can't simply rely on permissions of the logged in user.

I see two options:
1. Leave the hook. (#8776 as is)
2. Lock the resources/discussions/owner view down to displaying only listings for groups. To add user-centered discussions, the dev would have to override that view and impose his own limitations on types.

**Comment by juho-jaakkola** [comment] 2015-08-21 13:04
Closing because it was decided that we will not support user-centered discussions out of the box in Elgg 2.0.0. Also thanks to #8869 it will now be easier to implement the support in a plugin if necessary.

**Closed by juho-jaakkola** 2015-08-21 13:04 UTC
Labels: bug, usability
