### ISSUE TITLE
Relative times look goofy

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10272] opened 2016-09-23 21:36 UTC
From @ewinslow last year:

"a few seconds ago", "a few minutes ago", etc. This format has repeatedly felt annoying to me especially when the times are far back (1230 days ago? How is that helpful at all?). I don't know if I can give any objective evaluation of it, but it just seems goofy to me. I suspect perhaps that people don't think of past events in terms of "how many days ago" they happened. They think of them in terms of fixed dates that don't change. E.g. If I asked what you were doing "5084 days ago", that probably doesn't mean much to you, but if I asked what you were doing "Tuesday, September 11, 2001," that date might hold some more obvious significance (i.e. WTC terrorist attack).

I vote we use absolute times that just leave off unnecessary details as appropriate:
* Today at 5:30pm (any same-day activity)
* Yesterday at 5:30pm (any yesterday activity)
* Tuesday at 5:30pm (before yesterday, same week)
* Tuesday, September 11 (different week, same year) 
* Tuesday, September 11, 2001 (different year)

Future times are easy enough to cover, we just add:
* Tomorrow at 5:30pm (any activity happening on the next calendar day)

Hovering over the date could, as it does now, give you the fully specified time: "5:30pm Friday, August 14, 2015 PDT"

Would like to try this out on elgg.org and see if it improves the experience at all...

**Comment by jeabakker** [comment] 2016-09-24 08:23
PR #10246

**Comment by jdalsem** [comment] 2016-09-30 08:55
Duplicate of #9897

**Closed by jdalsem** 2016-09-30 08:55 UTC
