### ISSUE TITLE
elgg_get_excerpt breaks Unicode words

### ISSUE THREAD

**Issue by dranii** [Elgg/Elgg#7640] opened 2014-12-07 00:19 UTC
Particularly long unicode names or titles.
<code>$CONFIG->breadcrumbs[] = array('title' => elgg_get_excerpt($title, 100), 'link' => $link);</code> 
If a long unicode name has been entered by an end-user and it has to be truncated so as not to break display of breadcrumbs etc, the Unicode word gets broken

What I am meaning by 'breaking' of Unicode words: suppose  Äöüéèêë will show Äöüé�� instead of Äöü... This is just to illustrate - obviously this is not a long word but you can make <code>$CONFIG->breadcrumbs[] = array('title' => elgg_get_excerpt($title, 10), 'link' => $link);</code> and enter a long Unicode word in Indic characters and see how it is broken. English equivalent will be (though it never happens in English) 
![eluni1](https://cloud.githubusercontent.com/assets/9887635/5329492/b9362520-7dd5-11e4-9d67-632087b97be5.PNG)

**Comment by mrclay** [comment] 2015-01-27 01:48
If you have MB enabled (required for Elgg) it should not cut UTF-8 chars. However, CKeditor actively converts chars to HTML entities (I don't know why), which the function *does* cut. Before the elgg_substr() call we should decode HTML entities.

**Comment by dranii** [comment] 2015-02-09 12:01
what is  MB enabled

**Comment by mrclay** [comment] 2015-02-09 12:20
The mbstring extension

**Comment by dranii** [comment] 2015-02-09 12:44
I think it happens even if mbstring is enabled - need to test more

**Comment by jdalsem** [comment] 2016-10-26 07:43
We need more info to reproduce this problem. If you have this available please let us know. Closing this for now.

**Comment by mrclay** [comment] 2016-10-29 03:40
Reproduce by creating content with description `ÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéèÄöüéè`

CKeditor HTML-encodes these instead of leaving the UTF-8 characters, and since output/excerpt doesn't HTML-decode, you get: `Äö&uu...` instead of `Äöüéè...`

**Comment by mrclay** [comment] 2017-04-19 21:43
http://docs.cksource.com/ckeditor_api/symbols/CKEDITOR.config.html#.entities

**Closed** 2019-10-17 11:37 UTC
Labels: bug
