### ISSUE TITLE
Rich Text Editor's Link dialogue doesn't work within lightbox

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#8335] opened 2015-05-20 16:48 UTC
You can't focus on text inputs. This is a [known bug in jQuery UI dialog](http://bugs.jqueryui.com/ticket/9087), but the proposed solution didn't work for me.

**Comment by jdalsem** [comment] 2015-05-21 08:32
Any specific browser you have this issue with? Can't reproduce this with Firefox

**Comment by jdalsem** [comment] 2017-12-11 09:36
Closing this as i can not reproduce this

**Closed by jdalsem** 2017-12-11 09:36 UTC
