### ISSUE TITLE
Messages coming from groups

### ISSUE THREAD

**Issue by gerard-kanters** [Elgg/Elgg#9484] opened 2016-03-14 19:05 UTC
When a user starts a discussion, blog or whatever in a group and another user has site notifications on (which is default I believe)  the messages comes from "deleted users"

This is caused by : https://github.com/Elgg/Elgg/blob/2.x/mod/messages/views/default/object/messages.php#L18

```
$user = get_user($message->fromId);
```

which tries to get a user icon on a group guid in engine/lib/users.php

```
function get_user($guid) {
        return _elgg_services()->entityTable->get($guid, 'user');
}     
```

It is straightforward to fix 

```
$user = get_entity($message->fromId);
```

But that is how it used to be, the developer who changed it must have had a reason for doing that.
Maybe because one cannot reply on it by clicking on the group icon (where it is possible when it comes from a user) .

**Comment by mrclay** [comment] 2016-03-14 19:27
I changed it in https://github.com/Elgg/Elgg/commit/2e73cce7fb6cdf0fadbd6c417b2a96d3649bbec4#diff-4a658854cf8e7ccbf37b30c80f69f122L17, assuming that `->fromId` would always reference a user.

Why is a message being created and sent by a group? I thought only users could send messages.

**Comment by gerard-kanters** [comment] 2016-03-14 19:41
It is from notifications. Like a user starting  a discussion and site notification is on. The group is mentioned as the one sending the message, because the group entity is owner of all content in a group.

This should also appear in the community if users would use site notifications.

**Comment by mrclay** [comment] 2016-03-14 20:21
https://github.com/Elgg/Elgg/blob/2.x/mod/site_notifications/classes/SiteNotificationFactory.php
I see that Elgg creates a SiteNotification object, but I don't see why code handling ElggObject(messages) code would have anything to do with it. Are you sure you're prescribed change fixes the problem?

**Comment by gerard-kanters** [comment] 2016-03-14 20:33
I am not sure that sitenotifications is responsible. It was handled differently in older versions. Discussions where handled by groupforumtopic_notify_message in 1.8 

Maybe some plugins still use a similar structure or maybe this is related to upgrades. Anyway, to answer the question I am sure it fixes the problem.

**Comment by gerard-kanters** [comment] 2016-03-14 20:58
Anyway $from can still be a group, like with joining groups. I can not see how discussions are handled with notifications. This follows a long path.

**Comment by hypeJunction** [comment] 2016-03-15 10:06
I am soon to be working on a group inbox for one of my projects, where users can send message on behalf of a group, so I think user-only sender/recipient logic might be limiting. Will report back when I get to it.

**Comment by mrclay** [comment] 2016-03-16 16:00
I'll stop being cryptic: I don't feel comfortable making a change until we understand why execution is running through that code. Is there a change a 3rd-party plugin is creating these `messages` objects? If we're going to support that, we should document the edges of that support. E.g. can core support senders/recipients being groups? arbitrary entities? @juho-jaakkola any input?

**Comment by juho-jaakkola** [comment] 2016-03-28 12:44
Ever since Elgg 1.9 the `messages` plugin has not been used by Elgg core for sending notifications (in-site notifications were replaced by the `site_notifications` plugin). Most likely a third-party plugin for Elgg 1.8 had been creating the notification messages directly instead of using the core notification functions. And now it continues to do so even though core doesn't support messages as a notification method anymore.

Can you pinpoint which plugin is causing it? Once we know that, we can try to figure out what exactly is happening and why.

**Comment by jdalsem** [comment] 2017-11-09 13:37
Like the comment before describes that core is nowhere creating messages as a group, this must come from older functionality or a third party plugin. Closing this as it is not reproducable at this moment in a core situation AFAIK.

**Closed by jdalsem** 2017-11-09 13:37 UTC
