### ISSUE TITLE
How to handle private function access_get_show_hidden_status and access_show_hidden_entities

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7825] opened 2015-01-27 10:32 UTC
The functions `access_get_show_hidden_status` and `access_show_hidden_entities` are both marked as private. There is no good alternative to get/set this information in a *safe* way. Even core plugins use these private functions (like user_validation_by_email and messages). Any idea on how to replace these *unsafe* functions with a stable version?

**Comment by hypeJunction** [comment] 2015-01-27 10:44
I used this: https://gist.github.com/hypeJunction/c3984ac3ba870abd206a

**Comment by ewinslow** [comment] 2015-01-27 17:38
What is a typical use case for this? Ability to send email notifications to "disabled" users?

**Comment by beck24** [comment] 2015-01-27 17:49
@hypeJunction solution seems like overkill when when the function exists.  Any time you need to interact with something that's disabled you need to use it.
Plugin example: https://community.elgg.org/plugins/1508071

**Comment by jdalsem** [comment] 2015-01-27 19:18
> typical use case for this

- all kinds of user validation processes
- upgrade processes that should also update disabled entities
- functionality to change username (needs to check for usernames of disabled users)
- any functionality that lets content be enabled/disabled
- i can go on

**Comment by iionly** [comment] 2015-01-29 06:25
(Part of) the problem is (as has been discussed before for example at https://community.elgg.org/discussion/view/1847926/deleting-functions-marked-access-private) that these functions were not private when they were introduced but only made private functions later.

Usage of these functions (and a few others listed in the linked discussion) might come from them being used in bundled plugins (examples of how to implement certain things...). Usage of these functions also in bundled plugins clearly show the need for these functions.

How about reverting the former decision of making these private api functions public api functions again? This seems the easiest solution. Alternatives would be introducing new public api functions that add the same functionality (but break BC unnecessarily). Or dropping these private api functions (at some point) resulting in possibly dirty workarounds being added in plugins directly (even independently similar dirty solutions in different plugins).

**Comment by beck24** [comment] 2015-01-29 06:53
In this case I vote for making it public API

**Comment by mrclay** [comment] 2015-01-29 13:34
Closing in favor of #7838

**Closed by mrclay** 2015-01-29 13:34 UTC
Labels: dev usability
