### ISSUE TITLE
Userpicker is appending HTML to end of page

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8891] opened 2015-08-25 06:59 UTC
In Elgg 2.0 userpicker appends HTML to the end of the page when a user is selected from the list.

![userpicker](https://cloud.githubusercontent.com/assets/883920/9460550/f29bbbb0-4b0f-11e5-9a2e-c8a67afbcef3.png)

**Comment by mrclay** [comment] 2015-10-04 19:48
Duplicate of #8782

**Closed by mrclay** 2015-10-04 19:48 UTC
