### ISSUE TITLE
doesn't fetch the menu items (elgg_nav_collapse)

### ISSUE THREAD

**Issue by vikram06** [Elgg/Elgg#7657] opened 2014-12-11 11:56 UTC
doesn't fetch the any menu items (elgg_nav_collapse) button in aalborg_theme elgg 1.10

**Comment by jdalsem** [comment] 2015-02-16 22:33
closing this as there came no answer on previous comment

**Comment by zia-uddin** [comment] 2015-02-23 10:59
'blog/blog/view/728/.elgg-nav-collapse' URL not found in Google webmaster. please help me , how i can fix this problem.

**Comment by ewinslow** [comment] 2015-02-23 23:01
People are clicking the button before js is bootstrapped.

We should do something more reasonable in this situation...

**Comment by PerJensen** [comment] 2015-02-24 04:22
I think it's fixed already in  #7865

**Comment by jdalsem** [comment] 2015-02-24 07:52
yep i think so too

**Closed by jdalsem** 2015-02-24 07:52 UTC

**Comment by vikram06** [comment] 2015-02-25 06:15
Yes...fixed in #7865

**Comment by vikram06** [comment] 2015-02-25 06:36
I was faced same problem in elgg community site.when i click toggle button show 403 error.Is currently fixed #7865 in community site??...or one new issues??

**Comment by vikram06** [comment] 2015-02-25 06:38
Or reopen

**Comment by PerJensen** [comment] 2015-02-25 17:02
Community site hasn't been upgraded to 1.10 yet.

**Comment by vikram06** [comment] 2015-02-26 00:49
Okay.please open new issue for commuity site toggle does n't working.i think also issues in elgg 1.9 community site.when i click toggle button shows 403 error.

**Comment by jdalsem** [comment] 2015-02-26 07:57
As the issue is already fixed in 1.10, opening a new ticket is not needed. The only advice left is to update the community site to 1.10, but that work is not managed here.

**Comment by vikram06** [comment] 2015-02-26 13:24
+1
