### ISSUE TITLE
learn.elgg.org version switcher doesn't work

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9473] opened 2016-03-10 22:14 UTC
I don't see this code in our scripts:
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/static-src/core/js/doc-embed/sphinx.js

**Comment by juho-jaakkola** [comment] 2016-03-11 07:26
Its' funny that it starts working if you manually change the version in the URL: http://learn.elgg.org/en/1.9/

**Comment by mrclay** [comment] 2016-03-11 13:26
Only the 1.9 works :)

**Comment by iionly** [comment] 2016-09-07 18:09
Still not working. Additionally, the latest available docs (also the default shown) is for 2.0. And it's not only the change of version that is not possible: you also can't select a translation of the docs (granted not many available anyway and even less complete translations) and you also can't choose to download the docs because all these functionality is available via the menu only.

**Comment by juho-jaakkola** [comment] 2016-09-10 11:11
> the latest available docs (also the default shown) is for 2.0

Versions 2.1 and 2.2 hadn't been enabled yet. They should work now as soon as learnthedocs runs a build for them.

**Comment by juho-jaakkola** [comment] 2016-09-10 11:18
@mrclay What do you mean by "I don't see this code in our scripts"? Which scripts? Should that part be manually added somewhere to make the version switcher work?

**Comment by mrclay** [comment] 2016-09-10 13:50
Not sure at this point. I just knew when the switcher wasn't working, there was no script present to operate it. It wasn't an error.

**Comment by iionly** [comment] 2016-09-11 15:44
If the missing file would cause the issue, it wouldn't explain why it works for the 1.9 docs.

I've no idea how the Readthedocs installation works (I tried to figure out how it gets installed any even failed with that). Is the "flyout menu" served from learn.elgg.org or from the Readthedocs site (it seems that at least some scripts are pulled from there).

The question is also since when it failed to work or if it even worked at all for any other version in the past. Did the flyout menu fail already since 1.10 became available or has it stopped working since 2.0?

Maybe the problem is caused by some faulty configuration (either at Readthedocs, or at the learn.elgg.org installation). Or the flyout menu to work requires an update of the installation at learn.elgg.org.

**Comment by jeabakker** [comment] 2017-08-08 12:01
fixed with a322320a23d5261954ddeadb8702cd85cef61d57 in 2.3

**Closed by jeabakker** 2017-08-08 12:01 UTC
