### ISSUE TITLE
Dropdown login-box at the wrong place

### ISSUE THREAD

**Issue by vPriVate** [Elgg/Elgg#8931] opened 2015-09-13 22:18 UTC
In Elgg 2.0.0 alpha 2, after loading my site I click on "Log in" and the login dropdown-box appears, but at the wrong place (it is to deep). When I again click on "Log in" twice to reopen the dropdown-box, it appears at the correct place.

**Comment by mrclay** [comment] 2015-09-15 01:48
I've seen this happen but can't duplicate it. Is there a specific page and series of events to reproduce?

**Comment by vPriVate** [comment] 2015-09-16 08:09
No specific page or event, it happens directly after loading the site initially (landing page "activity" and a customized (hello world) home page consisting of a resource including a view).
My plugin is the only "not bundled" plugin installed and it is in an early development-state (no "real" coding).
Can't reproduce it with Firefox 40 or IE 10 at the moment, it occured with Safari on Mac as I opened the ticket (will try this again).

**Comment by jdalsem** [comment] 2016-04-13 07:20
Duplicate of #6452

**Closed by jdalsem** 2016-04-13 07:20 UTC
