### ISSUE TITLE
master fresh install Phinx timeout

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11645] opened 2018-01-22 15:04 UTC
Installing db took to long

**Comment by jdalsem** [comment] 2018-01-22 15:05
probably dupe of #11618

**Comment by jdalsem** [comment] 2018-01-22 15:09
or #11601

**Comment by jeabakker** [comment] 2018-01-22 15:26
this was during install, don't know if cache is used yet as there is no ready database yet
After finishing the (web) installer the first load of the site took a while which probably is what is described in #11618

**Closed** 2018-01-24 07:57 UTC
