### ISSUE TITLE
Widgets with no edit form still have clickable gear icon

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10915] opened 2017-04-13 15:50 UTC
Noticed in admin dashboard, but maybe all widgets.

cc @jdalsem @jeabakker

**Comment by hypeJunction** [comment] 2017-04-13 17:37
There should be a ticket about this already. I opened one at some point

**Comment by jdalsem** [comment] 2017-07-25 12:51
Duplicate of #10746

**Closed by jdalsem** 2017-07-25 12:51 UTC
