### ISSUE TITLE
Avatar Cropper not always allowing users to drag select across uploaded image.

### ISSUE THREAD

**Issue by cleverthings** [Elgg/Elgg#10986] opened 2017-07-10 19:40 UTC
This is a difficult one to reproduce, because it seems to be related to the caching and the timing of the javascript loading. Not all users will see the bug, and the problem even comes and goes with the same users and software/config - which is why I thought it might be caching or something. I have personally seen it happen on a Chrome Browser, but I can't locate a race condition or way to reliably reproduce it.

In my code, this is how I "fixed" it - but can someone else verify this is the right way to go?
In vendor/elgg/elgg/js/lib/ui.avatar_cropper.js
I wrapped the end of the elgg.avatarCropper.init function like this:
===========
    $(window).load(function () {
        $('#user-avatar-cropper').imgAreaSelect(params);
        if ($('input[name=x2]').val()) {
            $(window).on('load', function () {
                var ias = $('#user-avatar-cropper').imgAreaSelect({instance: true});
                var selection = ias.getSelection();
                elgg.avatarCropper.preview($('#user-avatar-cropper'), selection);
            });
        }
    })

**Comment by mrclay** [comment] 2017-07-10 20:12
Binding to window load instead of DOMready is fine by me. There aren't likely to be a ton of blocking resources loading on this page.

**Comment by jdalsem** [comment] 2018-12-14 13:08
unable to reproduce, so closing for now

**Closed by jdalsem** 2018-12-14 13:08 UTC
