### ISSUE TITLE
select-buttons located some dots left

### ISSUE THREAD

**Issue by lweddewer** [Elgg/Elgg#9287] opened 2016-01-06 12:25 UTC
Select buttons are postion some dots to wide left. 
Locks like the postion happens based on the inner button  not on the outer frame.

If a button is based leftmost the the overhanging part of the button is not showing.

As you can see both round and squared buttons are effected.
The picture was taken in the project plugin on the elgg.org community.
I have seen the same error in my own installation.

![260106_fehler_selectbutton](https://cloud.githubusercontent.com/assets/8478427/12142267/10e83bcc-b477-11e5-97fb-e7625b325077.png)

**Comment by mrclay** [comment] 2016-01-06 15:24
Duplicate of #6448

**Closed by mrclay** 2016-01-06 15:24 UTC
