### ISSUE TITLE
elgg3: custom_index vs. activity plugins index page and plugin priority issue

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12191] opened 2018-10-03 11:35 UTC
I see a strange issue with plugin priority in connection with custom_index and activity plugins.

I wondered why I don't get the custom_index index page but always only the activity page as index. Then I saw that custom_index is above activity in the plugin list so I placed custom_index below activity. STILL I got the activity page as index page. THEN I noticed that for whatever reason the plugin order has changed and custom_index got placed above the activity plugin!

So, the plugin order of these two plugins is not saved as expected. Additionally, the priority requirement (activity above custom_index) as defined in manifest.xml of custom_index wasn't followed correctly on site installation. But after disabling custom_index you can't enable it anymore because now custom_index wants to be placed below the activity plugin but when trying to fix the order it's not saved.

So, there's at least a problem with activity and custom_index. I can't say yet if the problem also occurs with other plugins.

**Comment by iionly** [comment] 2018-10-03 11:55
With activity plugin disabled I could re-activate the custom_index plugin. And flushing the cache after changing the order (with activity plugin still disabled) seemed to have somehow overriden the priority issue with custom_index. After re-activating the activity plugin the order was kept as expected.

So, it might be that a priority requirement of a plugin blocks the re-ordering of a plugin (even if the plugin order is wrong to begin with) instead of re-checking the requirement after the re-ordering.

**Comment by jdalsem** [comment] 2019-01-11 12:39
i am unable to reproduce this issue. closing this for now

**Closed by jdalsem** 2019-01-11 12:39 UTC
