### ISSUE TITLE
File upload API not fully cleaning up afterwards?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#11445] opened 2017-11-30 19:23 UTC
See also https://elgg.org/discussion/view/2720568/new-icons-moved-to-wrong-folder-location.

It's not related to hypeDropzone directly. Also, with Elgg's Files plugin there are some "extra" folders in the data directory after each file upload. These folders are created as
```
<bucket>/<entity_guid>
<bucket>/<entity_guid>/tmp
```
Both folders are empty and the uploaded file (also thumbnail files on image uploads) is available in
```
<bucket>/<user_guid>/file
```
as expected when using the Files plugin.

Could it be that the upload API doesn't clean up correctly and these folders remain?

**Comment by jdalsem** [comment] 2017-11-30 19:36
in master the temp file locations are moved to the systems temp files directory and the system than should do the cleanup. it is indeed correct that in Elgg 2.3 the temp folders are not removed. Are you experiencing problems with the lack of cleanup? Otherwise i would like to close this issue as it is already fixed in master

**Comment by iionly** [comment] 2017-11-30 19:44
For every upload a directory remains and pollutes the user data subtree. And it's rather impossible to clean it up manually. How diffifult would it be to backport the master behaviour or at least get the directories to be created not in between the user data directories, e.g. in a dataroot/tmp_uploads folder? Then you could easily clean up this folder manually.

**Comment by ci5aIo** [comment] 2017-11-30 19:52
(aka  [C0Rrupt](https://elgg.org/profile/thjMMvw))
The pollution of the data subtree is more extensive for images.  All image icons are saved to a subfolder as "data/<site_guid>/<image_guid>/icons/icon".  This is the problem that caused me to ask for your help.

**Comment by jdalsem** [comment] 2017-12-01 19:11
backporting the tmpfiles feature from master to 2.3 is not going to happen. I agree that the icon system increases the amount of empty folders, however empty folders were always there... my question is what is the problem? Only thing i can think of is maybe a slower backup job...

**Comment by iionly** [comment] 2017-12-02 13:06
Proposing https://github.com/Elgg/Elgg/pull/11450.

If the PR is not an acceptable option and/or for cleaning up existing empty folders would it be safe to suggest a regular execution of
```
find . -type d -empty | xargs rm -rf
```
in the data directory? This would find and delete empty folders (might be necessary to do twice to get rid of empty <entity_guid>/tmp folder structures created on file uploads).

My point with trying to fix this is that a few empty folders might not hurt much but on some sites there might be many thousand such folders created and then it gets at least slightly annoying. And 3.0 no longer creating these folders is not a satisfying solution as people might need to stay on 2.3 for quite some time even with 3.0 out (think of 3rd party plugins that need to be updated).

**Comment by ci5aIo** [comment] 2017-12-02 16:41
Every folder that the system creates for images has all of the newly created icons in it.  They aren't empty folders that can simply be deleted.

**Comment by hypeJunction** [comment] 2017-12-02 20:08
I believe there are tests against left over files. I don't care much for tmp directories, IMO not worth the trouble.

**Comment by jeabakker** [comment] 2017-12-04 08:08
> Every folder that the system creates for images has all of the newly created icons in it. They aren't empty folders that can simply be deleted.

then they aren't tmp images but images used by the user/system for (for example) icons. These files will be cleaned up when the user get's deleted

**Comment by ci5aIo** [comment] 2017-12-04 12:51
The thing is, there is a folder for every image.  Hundreds of thousands of folders, conceivably, for the life of the user.  Persistent folder pollution is the problem.  I'm unconcerned about the temporary folders so much.  They're really incidental.  I just want the resized icons to live in the folder of the owner ... one folder per user ... like it used to be.

**Comment by jdalsem** [comment] 2017-12-04 13:02
i have a hunch that your problem is not related to core, but to hypedropzone only...

**Comment by hypeJunction** [comment] 2017-12-04 13:04
Icon system is hookable, you can use hooks and rewrite paths as you please. IMO, it makes a lot more sense when entities own their own icons, so you don't have to play holla hoops to retrieve an icon "like it used to be"

**Comment by ci5aIo** [comment] 2017-12-04 13:13
OK, but the entities themselves are separated from their icons.  The file entity lives in the owner/files folder.

**Comment by hypeJunction** [comment] 2017-12-04 13:19
Only for BC reasons, that's changing in 3.0, I believe

**Comment by hypeJunction** [comment] 2017-12-04 13:23
If not, there is a ticket for it, and it would make more sense for the original file to live in its own directory. I don't see why data directory structure would bother anyone, you have a flexible API and you can redesign to fit your needs, but I don't see why anyone would bother. For that matter you can also say that the database is "polluted"

**Comment by iionly** [comment] 2017-12-04 18:40
Two (or maybe 3) issues got mixed up here.

Original issue (I thought the only issue at the time of opening the issue): Elgg 2.3 core with the new file upload API creates tmp folders of the form
```
<bucket>/<entity_guid>
<bucket>/<entity_guid>/tmp
```
used during processing the upload - and only for that purpose. Uploaded files (and thumbnails) get moved to the user's folder but the tmp folders remain (until the entity they were created for gets deleted). Proposed change in https://github.com/Elgg/Elgg/issues/11445 would be to use only a single tmp folder in ```<bucket>/<site_entity_guid>/tmp```. Seems not to hurt to do it that way and you have no useless clustering of tmp folders.

Second issue (the issue the discussion on the community site was opened for by @ci5aIo ) seems to be with hypeDropzone and/or hypeIcon only. As it seems, either one of these two plugins makes use of the ```<bucket>/<entity_guid>``` folder not only as tmp during upload but also as permanent saving location of the uploaded icon file(s) for the corresponding entity (if the files would be also saved in the user's folder it would be even stranger...). The hypeDropzone and hypeIcon plugins contain their own code for handling the upgrade (similar to Elgg core code but not exactly the same). I don't know the reason for doing it that way. Maybe it is kind of a backport of the Elgg 3.0 data directory saving scheme (if there has been a change in core here?). Anyway, it breaks the expected "traditional" scheme of "ALL files of ONE user in ONE folder". But the change to the old scheme of saving files would require modification of the plugins' code and not of Elgg core. I don't know if reporting it as an issue to the plugin repos would make much sense taking into account that @hypeJunction already posted here that he sees no reason for a change.

Possibly 3rd issue: is it really that Elgg 3.0 will save uploaded files in ```<bucket>/<entity_guid>``` folders separately of a user`s folder? I would like to see it with my own eyes instead of asking but I fail to get 3.0-dev to work currently due to out-of-memory fatal errors on post-install. Anyway, if the saving is done in separate ```<entity_guid>``` folders, what would be the advantage? Any performance gain? I can only think of the disadvantages that you wouldn't be able to easily save all uploaded data of a user by just saving the user's folder and you also can't easily check anymore if all user data got deleted when deleting the account.

**Comment by jdalsem** [comment] 2017-12-05 15:54
@iionly is right that 2 issues are getting messed up in this ticket. The problem with the path "data/<site_guid>/<image_guid>/icons/icon" is not something core does and probably comes from the related plugins.

The other issue is with the iconservice in Elgg that always creates a temp folder in the entity folder where the icon applies to. These folders are not removed. In Elgg 3.0 temp files will no longer be created in the dataroot, so these empty folders will not be created anymore in that situation.

Until Elgg 3.0 i would not want to change anything on this until i am **clear on what the problem is** with the empty folders. There are lots of reasons that Elgg could create an empty folder (for example if you remove your avatar, the 'profile' folder is left). If you want to clean up, your suggested script to remove empty folders is fine by me. Google will help you with that if you need more advice.

Extra info: _entity folders will be removed when the entity is deleted_

>  is it really that Elgg 3.0 will save uploaded files in <bucket>/<entity_guid> folders 

I want to clearify on this that Elgg has been able to save data with the object entities instead of with a user since 1.9 (See https://github.com/Elgg/Elgg/pull/5111/commits/b94fb463d8ee22c399f4723b54470aa8969209ad)

A lot of datastorage of icons have been moved from the user to the entity, for example the group icons. This makes transfering of ownership much easier as related icons do not have to be moved between users.

I believe the file plugin has not yet changed the storage location of the files, so the files uploaded with the file plugin are in 3.0 still saved in the owners dataroot folder.

Saving entity related files with the entity is the best practice at this moment. A lot of plugins already use that practice, for example the event_manager or blog tools plugin.

Closing this issue as i see nothing to fix. Please keep commenting if you can clarify the problems.

**Closed by jdalsem** 2017-12-05 15:54 UTC

**Comment by iionly** [comment] 2017-12-05 18:41
The problem I see with the tmp folders is that I just don't see any reason for these tmp folders to be created in the first place separately for each entity when these folders have no other purpose than being a temporary save location for the files during processing the upload before they get moved to their final location. After that these tmp folders have never again any use. Also, the difference between these tmp folders to other folders like the profile folder is that there might be one empty profile folder per user but there could be a countless number of these tmp folders per users.

The PR I suggested would simply use a single tmp folder (in the site_entity's data folder) to be used as collective temporary storage location. This change doesn't have any implication regarding the final storage location, i.e. the files could still be saved in "entity_guid" folders without any problems if that's where the dev wants them to be saved.

I find it odd to reason with the change in the upcoming 3.0 to decline the PR I made for the 2.3 branch. Elgg 3.0 isn't even out yet and even then the 2.3 branch will become LTS and most likely people have to stay on 2.3 for some (long?) time in most cases (until 3rd party plugins are being made compatible for 3.0, because they might not be able to update to PHP 7 etc.). If the separate tmp folders isn't an issue on Elgg 3.0 anymore that's fine. But it remains an issue on 2.3 as long as it's used.

And again: the tmp folders issue is not the same as separate folders for entities (these only happen to be also empty now with the files plugin files being moved to the user's file folder).

As to saving the entities' files separately I can understand that it seems to make some things easier to handle from the Elgg engine side (like changing owner). But it could be handled (already has been handled) by the engine up to now. On the other hand this change makes it impossible to collect all of a user's files from the shell. The shell does not know about which entity belongs to whom. The analogy between "pollution" of the data directory and the database is also a rather lopsided because you can retrieve the user owned data from the database with e_get* functions whereas you have no corresponding tools for the files on the shell. And I don't see a "user files export" plugin as a good alternative either because such a plugin would have to be customized for each site depending on the plugins used that might save files. With all files of a user in one folder it's just as simple as it can be. But I guess I'm tilting against windmills here.
