### ISSUE TITLE
Elgg 3.1 - Activity Route Issue

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#12782] opened 2019-07-25 18:22 UTC
I have just installed a fresh copy of elgg 3.1 in my local system using composer.
I found that "Activity" plugin route is not working properly.

I have installed elgg under `http://localhost/www/ck_31` so ideally the activity page menu link should be `http://localhost/www/ck_31/activity` but the "`www/ck_31`" is getting repeated twice and the menu is actually calling "`http://localhost/www/ck_31/www/ck_31/activity`"

![image](https://user-images.githubusercontent.com/2772844/61898318-a8681900-af36-11e9-864b-7846d4e2749d.png)

Steps for fresh copy of elgg setup:
- composer create-project elgg/starter-project:dev-master ./path/to/my/project
- cd ./path/to/my/project
- composer install

Did i miss out something?

**Comment by rohit1290** [comment] 2019-07-26 03:09
The same url route issue is with event_manager plugin as well.

**Comment by hypeJunction** [comment] 2019-07-26 07:11
Put `$CONFIG->wwwroot` into `settings.php`

**Comment by RiverVanRain** [comment] 2019-07-26 08:52
Confirmed.

> Put $CONFIG->wwwroot into settings.php
There is already and don't help.

**Comment by RiverVanRain** [comment] 2019-07-26 09:08
Same issue on the `admin/security `page tab `admin/security/information` ans some plugin' menu items at the admin section (e.g. Utilities -> Manage static page for [Static](https://github.com/ColdTrick/static)  plugin)

**Comment by rohit1290** [comment] 2019-07-27 05:21
The problem is caused by https://github.com/Elgg/Elgg/pull/12727/

**Comment by hypeJunction** [comment] 2019-07-29 16:57
The whole thing is caused by normalizing routes. IMO, routing system should be agnostic to site's location, so I'd suggest to rever that change, as oppose to trying to fix an issue that is not an issue.

**Comment by jdalsem** [comment] 2019-08-02 07:04
will be fixed in the next release

**Closed by jdalsem** 2019-08-02 07:04 UTC
