### ISSUE TITLE
lightbox css not loaded correctly in master branch

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#8466] opened 2015-06-12 15:09 UTC
a lot wrong with line 1622 in lib/views.php... no time to figure out what it is...

**Comment by jeabakker** [comment] 2015-06-12 15:10
introduced in https://github.com/Elgg/Elgg/commit/86f0a5d16d971078b118d95e2896ddf95d984c08#diff-5bbefe66200525a450e1eac0ebf4e21cR190

**Comment by mrclay** [comment] 2015-06-12 16:26
Dupe of #8416

**Closed by mrclay** 2015-06-12 16:26 UTC
