### ISSUE TITLE
Elgg\I18n\Translator->getInstalledTranslations() causes lots of notices

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9236] opened 2015-12-15 14:55 UTC
Al lot of notices like
> NOTICE: Missing el translation for "el" language key

reason: https://github.com/Elgg/Elgg/blob/2.x/engine/classes/Elgg/I18n/Translator.php#L409

it should first check if the language key exists before calling it

**Comment by jdalsem** [comment] 2016-04-13 08:16
Duplicate of #8561 and fixed in #9666

**Closed by jdalsem** 2016-04-13 08:16 UTC
Labels: easy, i18n
