### ISSUE TITLE
Invalid requirements in Master

### ISSUE THREAD

**Issue by jcanadas** [Elgg/Elgg#8492] opened 2015-06-15 14:24 UTC
It looks like some new required packages were added to composer.json but something is wrong.
It seems that several of the packages are not valid, or have invalid versions. 
The follow errors occur when composer is run on head:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/jquery could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package bower-asset/jquery-ui could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package bower-asset/text could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package bower-asset/requirejs could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package bower-asset/jquery-form could not be found in any version, there may be a typo in the package name.
  Problem 6
    - The requested package bower-asset/jquery-colorbox could not be found in any version, there may be a typo in the package name.
  Problem 7
    - The requested package bower-asset/jquery-migrate could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

**Comment by jcanadas** [comment] 2015-06-15 14:37
I think this issues stems from this check in
https://github.com/Elgg/Elgg/commit/86f0a5d16d971078b118d95e2896ddf95d984c08#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by juho-jaakkola** [comment] 2015-06-15 15:02
Did you run this first:
```
composer global require fxp/composer-asset-plugin:~1.0
```

**Comment by jcanadas** [comment] 2015-06-15 15:11
I did not but isn't the point of composer to manage the dependencies?

**Comment by juho-jaakkola** [comment] 2015-06-15 19:07
Yes, and running that command allows it to manage also javascript dependencies besides PHP dependencies.

**Comment by mrclay** [comment] 2015-06-15 19:19
This should be added prominently to the install/contrib docs.

**Comment by iionly** [comment] 2015-06-15 20:52
Currently the info is only available in docs/guides/javascript.rst which is not the place you would search first. I was stuck with the problem of a simple "composer install" not working anymore last week, too, and I searched the Internet for a solution as I thought the problem was due to an issue with composer. I happened to find the solution - and only afterwards (about 1 hour...) found the info in the Elgg docs.

**Comment by ewinslow** [comment] 2015-06-16 09:56
This is in the installation docs under installing from source. https://github.com/Elgg/Elgg/blob/master/docs/intro/install.rst

Since it is a bootstrapping issue I'm not sure how we get ahead of it. Wonder if a pre-install-cmd would work?

**Comment by ewinslow** [comment] 2015-06-16 09:57
Closing this issue since the requirements are valid. Reopen another ticket if you have a specific suggestion for how else to improve this situation.

**Comment by brettp** [comment] 2015-06-18 14:26
Reopening because the problem is this wasn't called out as a breaking change for devs and is not prominent in the docs. How would developer know they need to do this?

**Closed** 2015-06-18 23:32 UTC
Labels: dev usability
