### ISSUE TITLE
WSOD on egefac() with metadata_names

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8567] opened 2015-06-22 16:01 UTC
Not unique table/alias: 'n_table'

**Comment by hypeJunction** [comment] 2015-06-22 16:02
Working with 1.11

**Comment by hypeJunction** [comment] 2015-06-22 16:05
This only applies to ```'count' => true```. I suspect thiscomes from refactor in https://github.com/Elgg/Elgg/pull/7964. I guess we need to extend the scope of tests.

**Comment by mrclay** [comment] 2016-07-28 16:16
Duplicate of #5515

**Closed by mrclay** 2016-07-28 16:16 UTC
