### ISSUE TITLE
page and page_top entities should be merged in search results

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10638] opened 2016-12-01 16:13 UTC
See discussion and discussion replies on how to fix

**Comment by hypeJunction** [comment] 2016-12-01 16:15
They should really become the same thing, with page top as metadata

**Comment by jdalsem** [comment] 2016-12-01 16:17
feel free to do that... i think a search hook to merge page into page_top results (so there is only one type of searchable page) is a quick and easy one... merging page and page_top is a bit more work

**Comment by hypeJunction** [comment] 2016-12-01 16:20
Nah. I never use pages.

**Comment by jdalsem** [comment] 2016-12-01 16:26
the only thing bothering me is the search... so that needs to be fixed

**Comment by iionly** [comment] 2016-12-06 11:04
I've given it a try (page_top registered for search and page subtype merged in search). Combining the search results works. The problem is that the results both for top pages and subpages are listed now under "Top-level pages" (language string 'item:object:page_top' => 'Top-level pages') and this might be misleading at least. Changing the wording from "Top-level pages" to just "Pages" would surely result in confusion elsewhere.

So, I think it's either merging page-top into page searches or not combining the results at all.

**Comment by jdalsem** [comment] 2016-12-07 07:47
Yep. Merging them so the results show under 'Pages' makes the most sense.

**Comment by hypeJunction** [comment] 2016-12-07 08:06
We can just add new labels prefixed with search: and fallback if no key exists

**Comment by jdalsem** [comment] 2016-12-07 08:17
Nah no need to introduce new language keys.

**Comment by iionly** [comment] 2016-12-07 19:18
PR at https://github.com/Elgg/Elgg/pull/10641.

**Closed** 2016-12-13 14:36 UTC
Labels: easy
