### ISSUE TITLE
Problem with get_entity_relationships()

### ISSUE THREAD

**Issue by codelust** [Elgg/Elgg#5128] opened 2013-02-23 05:29 UTC
Elgg Version: 1.8.13, 1.7

### Scenario:

Take the case of two entities -- entity_1 and entity_2, which are attached with an arbitrary relationship - relationship_1.

Disable entity_1.

### Expected Behaviour

A call made to get_entity_relationships() on entity_2 does not return relationship_1.

### Actual Behaviour

A call made to get_entity_relationships() on entity_2 returns relationship_1. 

This will result in a fatal error in any code that tires to call any methods on the entity formed from get_entity() on entity_1_guid.

### Solutions:

1. Add 'enabled' field in entity_relationship table and update the get_entity_relationships() function. (probably the most efficient). Add a 'disableRelationships' method similar to 'disableMetadata' to cascade disables in relationships too.

2. Introduce a check in get_entity_relationships() to ensure that the row is not returned if guid_one or guid_two is not enabled. This will be terribly slow on big data sets as it will require the creation of two additional objects per call.

3. Use code within plugins to work around this, do the check in (2). But this adds up to a lot of unnecessary replicated checks for ElggEntity instances. 

In fact, if we can guarantee that any elgg_get_* calls will only return valid ElggEntity objects when it does not return FALSE, a lot of unnecessary code can be pulled out of the codebase.

**Comment by ewinslow** [comment] 2015-01-06 02:02
@codelust @mrclay is this still an outstanding issue that needs to be addressed, or should we call this working as intended?

**Comment by mrclay** [comment] 2015-01-06 03:56
I'd be OK closing. get_entity() should not be relied upon to return an entity.

**Comment by mrclay** [comment] 2015-01-06 03:57
...and while egefr() could be enhanced to serve this particular use case it doesn't seem that common.

**Closed by mrclay** 2015-01-06 03:57 UTC
Labels: bug
