### ISSUE TITLE
Elgg 4.0.0 fail to load post upgrade

### ISSUE THREAD

**Issue by jameswill** [Elgg/Elgg#13692] opened 2021-09-25 09:16 UTC
Hi,

I have recently upgraded my Elgg 3.3.21 to 4.0.0 However post upgrading successfully when I visit admin panel and Elgg site, it's not redirecting to there actual address and loads for indefinite time resulting in following error by firefox.

**a web page is slowing firefox --> stop**

This happens with chrome as well.

What could be the solution for this ?

Also I have not found any documentation regarding the upgrade of Elgg 3.3.x to 4.0.0 So I followed the step I used to follow to upgrade 3.x.x to 3.x.x If there are written docs on how to perform upgrade would be very helpful.

**Comment by RiverVanRain** [comment] 2021-09-25 12:17
> I have not found any documentation regarding the upgrade of Elgg 3.3.x to 4.0.0

https://learn.elgg.org/en/stable/appendix/upgrade-notes/3.x-to-4.0.html

> I followed the step I used to follow to upgrade 3.x.x to 3.x.x

It could be the cause of your issue.

**Comment by jameswill** [comment] 2021-09-27 06:58
Do Elgg 4.0.0 have manual upgrade notes ? Just like it has for Elgg 2.3 to 3.x ? [https://learn.elgg.org/en/stable/admin/upgrading.html#b-manual-upgrade-legacy-approach]()

As I am on a shared hosting environment and does not have root access to execute the command via CLI

**Comment by jdalsem** [comment] 2021-09-27 07:15
Did you run upgrade.php?

**Comment by jdalsem** [comment] 2021-09-27 07:18
There are no special instructions for upgrading 3.3 to 4.0. The same steps apply as you upgraded from 2.3 to 3.3. Any error message in your server error logs? It sounds like a redirect issue... could indicate something wrong in your htaccess.

**Comment by jdalsem** [comment] 2021-09-30 14:18
Any update on this?

**Comment by jdalsem** [comment] 2021-11-24 13:44
@jameswill any more details? Were you able to analyze this?

**Comment by jdalsem** [comment] 2021-11-29 14:22
Closing this as we need more information

**Closed by jdalsem** 2021-11-29 14:22 UTC
