### ISSUE TITLE
default_page_owner_handler breaks for Chinese username

### ISSUE THREAD

**Issue by enraiser** [Elgg/Elgg#8058] opened 2015-03-12 09:52 UTC
go to function default_page_owner_handler  in engine/lib/pageowner.php

almost at line 139

search for
 // @todo feels hacky

I did replaced $segments = explode('/', get_input('page', FALSE))

and replaced $segments[1 ]  with $segments[0]
and replaced $segments[2]   with $segments[1]

the testcases is line this
make a chinies username,
then click on thewire of that chinies username, it will get redirected to thewire/all

**Comment by juho-jaakkola** [comment] 2015-03-12 10:33
I'm not able to reproduce the problem. What are you using as the username?

**Comment by juho-jaakkola** [comment] 2015-03-12 10:38
This has been fixed in Elgg 1.8.17 283106afa1fb6ff9984341b8911f90c5d4e4c4a2

**Closed by juho-jaakkola** 2015-03-12 10:38 UTC

**Comment by juho-jaakkola** [comment] 2015-03-12 10:40
Elgg 1.8.16 was mentioned in the conversation: https://community.elgg.org/discussion/view/2057557/can-a-username-be-unicode
