### ISSUE TITLE
Obsolete elgg_register_js and elgg_register_css in favor of static views at the canonical location

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8487] opened 2015-06-15 09:43 UTC
If there is a view called `css/view` (hopefully soon `css/view.css` or even better just `view.css`, see #8382), it seems superfluous to have to call `elgg_register_css` before `elgg_load_css`. Elgg should just automatically name the CSS file based on their view path like it does with AMD modules, which we don't have to register explicitly.

Same goes for elgg_register_js/elgg_load_js, though I suppose those are all but deprecated at this point because of AMD...

**Comment by hypeJunction** [comment] 2015-06-15 09:46
+1. It's always a hassle to come up with a name. The problem is that css/js assets reside in the vendors lib most of the time. I suppose we can change the convention to keep vendors/ in views/vendors/.

**Comment by mrclay** [comment] 2015-06-15 12:37
I'm fine with having elgg_load_css/js automatically point to a view if none is registered.

**Comment by ewinslow** [comment] 2015-06-16 20:13
@hypeJunction I'd prefer we not encourage people to put vendors/ code into their views directory. In fact if we can convince everyone to use bower-asset/* composer deps, then they'll automatically go in the top directory anyways and never get checked into the plugin's repo at all.

I also don't want to load `jquery` as `elgg_require_js('vendors/jquery')`, or `require('vendors/jquery')`. I just want to say `require('jquery')`.

That said the fact that many many JS/CSS resource are outside the views system entirely is a good point and one we need a more straightforward solution for.

**Comment by hypeJunction** [comment] 2015-06-16 22:28
I am all for bower/composer, but currently we have to define any third party libs we use within a plugin, so we need to know where it resides. If the assets would suddenly move to the root level, we would have to redefine all paths, unless that happens magically somewhere else. T

**Comment by hypeJunction** [comment] 2015-06-16 22:30
Resolving this would also solve https://github.com/Elgg/Elgg/issues/8113

**Comment by ewinslow** [comment] 2015-06-17 00:35
> currently we have to define any third party libs we use within a plugin

Plugins can be composer required too.

**Comment by ewinslow** [comment] 2015-06-17 00:38
See also #8431. Elgg itself should (IMO) be installed with composer (we have to make changes to support that), and plugins certainly can/should be installed with composer so all their deps can be pulled in automatically and stored in a canonical location.

I want to put an end to any more references to /mod/...

**Comment by mrclay** [comment] 2016-08-09 03:42
Simple solution:

```php
function elgg_require_css($view) {
	$key = "elgg_require_css:$view";
	elgg_register_css($key, elgg_get_simplecache_url($view));
	elgg_load_css($key);
}

function elgg_unrequire_css($view) {
	$key = "elgg_require_css:$view";
	elgg_unregister_css($key);
}
```

**Closed** 2019-05-23 09:12 UTC
