### ISSUE TITLE
WSOD when searching for "event calendar" on community site

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#7984] opened 2015-02-21 10:49 UTC
It happens for the search string "event calendar" but not for the queries "event" or "calendar" or for example "event bla".

My guess is that the WSOD when search for "event calendar" might have something to do with the recent transfer of ownership of the Event calendar plugin and/or "Event calendar" group from Kevin to @juho-jaakkola. But maybe I'm wrong and the reason is something different. Regardless what the reason is I would say there should be a WSOD regardless whatever entered as search string.

**Comment by jdalsem** [comment] 2015-03-11 21:56
this is still the case... can anyone fix this? @Elgg/owners

**Comment by beck24** [comment] 2015-03-11 22:10
This is the cause: Call to a member function getType() on a non-object in /path/mod/search/views/default/search/object/comment/entity.php on line 15

**Comment by beck24** [comment] 2015-03-11 22:12
So the issue is that non-admin users have access to a comment, but the container of that comment is not visible to them.
This is another reason for making comment access sync to that of the container...

**Comment by beck24** [comment] 2015-03-11 22:13
https://github.com/Elgg/Elgg/issues/7807

**Comment by mrclay** [comment] 2015-03-16 12:51
We should audit all the views (particularly river and comment views) for calls of methods that request objects that may or may not return them (e.g. anything with an underlying `get_entity()`). Each call should verify a returned object and either silently `return;` or issue a warning visible to admins if the expected object isn't returned.

**Comment by mrclay** [comment] 2015-03-16 12:56
...i.e. we should consider methods like getContainerEntity() and getTargetEntity() just as untrustworthy as get_entity().

**Comment by ewinslow** [comment] 2015-03-17 05:08
:+1:

**Comment by jeabakker** [comment] 2015-03-17 09:18
> ...i.e. we should consider methods like getContainerEntity() and getTargetEntity() just as untrustworthy as get_entity().

:+1:

**Comment by jdalsem** [comment] 2015-03-24 08:12
can this one be closed? as #8062 is merged

**Closed** 2015-03-24 10:56 UTC
Labels: in progress
