### ISSUE TITLE
Form controls do not have labels

### ISSUE THREAD

**Issue by mfairchild365** [Elgg/Elgg#9400] opened 2016-02-17 16:30 UTC
Form controls MUST have associated labels for accessibility reasons. 

An example of a control that does not have a label: https://github.com/Elgg/Elgg/blob/7601a71a999a769bcfb618be59dbe3a45b2841bd/views/default/core/settings/account/password.php#L17

It looks like there are a few tickets open for this already:
https://github.com/Elgg/Elgg/issues/6743
https://github.com/Elgg/Elgg/issues/6356
https://github.com/Elgg/Elgg/pull/9086

There is even a milestone: https://github.com/Elgg/Elgg/milestones/Revamp%20forms/actions

However, it appears that work on this might have stalled. Is this still being worked on? Is there a target date/version for this to be fixed?

**Comment by mrclay** [comment] 2016-02-17 16:40
Duplicate of #6743.

**Closed by mrclay** 2016-02-17 16:40 UTC
