### ISSUE TITLE
elgg 2 feature request: Consolidated in-place upload of images on editor

### ISSUE THREAD

**Issue by isoguci1** [Elgg/Elgg#8678] opened 2015-07-02 16:16 UTC
Currently (elgg 1.9) there are two ways of adding an image to a text (discussion or blog):
1. Via the "embed content" link (via Embed 1.9 plugin) just outside the edit area box. 
   It allows the use of existing images of the user as well as letting user upload a new image file and use is in one go. This is a Wordpress like functionality.
2. Via the image icon on the tool bar of the text editor. 
   Currently on the default editor of Elgg, there is an image icon on the editor tool bar. But when user clicks on it, it ony supports the embedding of images already uploaded somewhere (via URL). For most users, this is a source of confusion and does not really fit todays' norms of UI behaviour.

First of all, there is a distribution of (cluttered) operations for the same function of embedding an image in a text file. When there are more than one way of doing the same thing, it is always confusing for users. 

Ideal way would be:
The image icon on the editor also letting the "upload" of an image, next to the URL one (probably upload having more precedence on the UI than the URL one, as users are _much more_ used to it from other systems like Twitter, facebook etc). And probably it would be a good idea to let admin disable the URL upload. In this case, admin would be able to disable the "embed content" link out of the text box.

Although the preferred solution, if this is a technologically challenging one with prohibitive amount of work, then the "embed content" link would be a fallback (though the location of the link is a bit out of workplace/context), in which case, it would be good to be able to disable the image icon on the editor tool bar (probably already possible via editor -CKeditor?-specific configuration?).

**Comment by mrclay** [comment] 2015-07-02 16:43
Or allow specifying a URL in the Embed popup.

**Comment by jdalsem** [comment] 2022-03-18 12:01
Closing as duplicate of https://github.com/Elgg/Elgg/issues/6095

**Closed by jdalsem** 2022-03-18 12:01 UTC
